name: Delay CI

on:
  schedule:
    - cron: "*/5 * * * *"

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    DISABLE_WORKFLOW_URL: https://api.github.com/repos/zhangc110033/xiaoMing/actions/workflows/delay.yml/disable

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: print something
        run: echo "run after 2 minutes..."

      - name: Enable workflow
        run: |
          curl -L \ 
          -X PUT \ 
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          $DISABLE_WORKFLOW_URL
